2blog.14790897.xyz {
	# Default proxy everything else to Ghost
	handle {
		reverse_proxy localhost:2368
	}
    	# Optional: Enable gzip compression
	encode gzip

	header {
        # Enable HSTS
        Strict-Transport-Security max-age=31536000;
        # Enable XSS protection
        X-XSS-Protection "1; mode=block"
        # Prevent MIME sniffing
        X-Content-Type-Options nosniff
        # Referrer policy
        Referrer-Policy strict-origin-when-cross-origin
        # Prevent embedding in external iframes
        Content-Security-Policy "frame-ancestors 'self' {$ADMIN_DOMAIN:}"
    }
}

:443 {
    respond "Forbidden" 403
}

# 4. 80端口自动跳转到 HTTPS
http://*.14790897.xyz {
    redir https://{host}{uri} permanent
}